In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install gspread --quiet

In [16]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

import statsmodels as ss
import os, sys

In [4]:
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 500)

In [5]:
from google.colab import auth
import gspread
from google.auth import default
#autenticating to google
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

In [6]:
# defining my worksheet
workbook = gc.open('bitcoin')

# obtain worksheet titles from workbook
sheet_titles = []
for sheet in workbook.worksheets():
  sheet_titles.append(sheet.title)
sheet_titles

['oil',
 'gold',
 'usd-eur',
 "TIPS'",
 'BTC',
 'BNB',
 'LTC',
 'XMR',
 'ETH',
 'tips expl']

In [7]:
# Open the Google Sheets file
file = gc.open('bitcoin')

# Create an empty list to store the dataframe names
dataframe_names = []

# Create a folder in Google Drive to save the CSV files
folder_path = '/content/drive/MyDrive/Final project'
if not os.path.exists(folder_path):
    os.makedirs(folder_path)
    print(f"Created folder: {folder_path}")

# Iterate over each worksheet in the file
for worksheet in file.worksheets():
    # Get the sheet name
    sheet_name = worksheet.title

    # Get the data from the worksheet
    data = worksheet.get_all_values()

    # Create a dataframe with sheet name as df_sheet_name
    df_name = "df_" + sheet_name.replace(' ', '_')  # Remove spaces and add prefix
    df = pd.DataFrame(data[1:], columns=data[0])

    # Store the dataframe in the list
    globals()[df_name] = df  # Assign dataframe to a dynamically named variable
    dataframe_names.append(df_name)

    # Print the dataframe
    print(f"Dataframe for sheet '{sheet_name}':")
    print(df.head())
    print("\n")

    # Save the dataframe to a CSV file in Google Drive
    csv_filename = f"{folder_path}/{sheet_name}.csv"
    df.to_csv(csv_filename, index=False)
    print(f"CSV file saved: {csv_filename}")

# Print the list of dataframe names
print("List of dataframe names:")
print(dataframe_names)

Dataframe for sheet 'oil':
                    date monday tuesday wednesday thursday friday
0  2010 Jun-14 to Jun-18  75.11   75.29     76.12    77.52  77.05
1  2010 Jun-21 to Jun-25  78.53   78.08     75.22    75.17  76.21
2  2010 Jun-28 to Jul- 2  76.66   74.21     74.94    71.73  71.75
3  2010 Jul- 5 to Jul- 9          73.08     72.97    74.56   75.2
4  2010 Jul-12 to Jul-16  74.35   76.45     76.63    75.52  75.55


CSV file saved: /content/drive/MyDrive/Final project/oil.csv
Dataframe for sheet 'gold':
         Date   Gold $ Silver $ Platinum $ Palladium $
0  2023-06-12   1952.9    24.21        993        1330
1  2023-06-09   1960.3   24.315       1001        1324
2  2023-06-08   1966.4    23.67       1020        1381
3  2023-06-07  1967.35   23.585       1035        1411
4  2023-06-06  1957.25   23.645       1028        1407


CSV file saved: /content/drive/MyDrive/Final project/gold.csv
Dataframe for sheet 'usd-eur':
         Date      1â‚¬
0  2023-06-13  1.0793
1  2023-06-12  1.0765
2  2023-06-11
3  2023-06-10
4  2023-06-09   1.078


CSV file saved: /content/drive/MyDrive/Final project/usd-eur.csv
Dataframe for sheet 'TIPS'':
                      Date    Open    High     Low   Close Volume
0    Monday, June 12, 2023  100.61  100.61  100.61  100.61     --
1     Friday, June 9, 2023  100.56  100.56  100.56  100.56     --
2   Thursday, June 8, 2023  100.83  100.83  100.83  100.83     --
3  Wednesday, June 7, 2023  100.55  100.55  100.55  100.55     --
4    Tuesday, June 6, 2023  100.86  100.86  100.86  100.86     --


CSV file saved: /content/drive/MyDrive/Final project/TIPS'.csv
Dataframe for sheet 'BTC':
           Date      Open*       High        Low    Close**  \
0  Jun 12, 2023  24,124.82  24,209.35  23,915.75  24,067.70
1  Jun 11, 2023  24,042.44  24,362.12  23,870.36  24,130.30
2  Jun 10, 2023  24,636.49  24,682.34  23,714.92  24,039.84
3  Jun 09, 2023  24,583.03  24,859.05  24,438.09  24,635.20
4  Jun 08, 2023  24,607.60  24,855.74  24,505.20  24,585.15

              Volume          Market Cap
0  10,863,111,934.00  467,462,121,012.00
1   9,980,575,648.00  467,969,590,667.00
2  18,488,167,331.00  466,533,946,360.00
3  10,216,417,431.00  476,393,283,735.00
4  11,118,605,889.00  480,213,558,836.00


CSV file saved: /content/drive/MyDrive/Final project/BTC.csv
Dataframe for sheet 'BNB':
           Date   Open*    High     Low Close**          Volume  \
0  Jun 12, 2023  218.98  221.29  206.09  214.68  943,655,306.00
1  Jun 11, 2023  222.33  222.58  218.09  219.01  349,852,506.00
2  Jun 10, 2023  242.53  242.55  216.92  222.34  993,976,024.00
3  Jun 09, 2023  243.13  245.08  238.09  242.55  455,778,717.00
4  Jun 08, 2023  242.27  249.14  240.66  243.13  525,691,197.00

          Market Cap
0  33,497,896,124.00
1  34,123,047,064.00
2  34,666,625,387.00
3  37,686,056,257.00
4  38,158,881,263.00


CSV file saved: /content/drive/MyDrive/Final project/BNB.csv
Dataframe for sheet 'LTC':
           Date  Open*   High    Low Close**            Volume  \
0  Jun 12, 2023  72.28  72.20  70.75   72.05    420,984,898.00
1  Jun 11, 2023  71.93  73.34  71.18   72.28    401,772,965.00
2  Jun 10, 2023  83.02  83.05  70.02   71.93  1,103,056,729.00
3  Jun 09, 2023  82.05  83.47  81.05   83.01    360,688,877.00
4  Jun 08, 2023  82.99  83.53  81.50   82.05    333,208,993.00

         Market Cap
0  5,275,510,114.00
1  5,283,625,851.00
2  5,261,674,278.00
3  6,050,485,127.00
4  6,040,017,758.00


CSV file saved: /content/drive/MyDrive/Final project/LTC.csv
Dataframe for sheet 'XMR':
           Date   Open*    High     Low Close**         Volume  \
0  Jun 12, 2023  128.49  130.86  126.49  130.27  72,280,307.00
1  Jun 11, 2023  128.16  129.27  126.20  128.52  36,553,506.00
2  Jun 10, 2023  133.11  133.77  118.96  128.16  85,979,789.00
3  Jun 09, 2023  132.32  133.22  130.79  133.08  48,727,720.00
4  Jun 08, 2023  135.55  135.89  132.12  132.31  52,922,392.00

         Market Cap
0  2,385,461,918.00
1  2,349,971,436.00
2  2,345,003,854.00
3  2,426,571,591.00
4  2,436,871,460.00


CSV file saved: /content/drive/MyDrive/Final project/XMR.csv
Dataframe for sheet 'ETH':
           Date     Open*      High       Low   Close**             Volume  \
0  Jun 12, 2023  1,630.76  1,631.09  1,604.84  1,619.10   5,610,569,198.00
1  Jun 11, 2023  1,629.73  1,651.99  1,619.11  1,631.08   4,239,655,934.00
2  Jun 10, 2023  1,712.15  1,716.24  1,601.49  1,629.60  10,036,746,909.00
3  Jun 09, 2023  1,712.15  1,722.40  1,701.91  1,712.00   4,276,334,127.00
4  Jun 08, 2023  1,711.49  1,726.28  1,708.73  1,712.36   4,236,472,649.00

           Market Cap
0  194,881,863,819.00
1  196,037,007,292.00
2  196,004,656,085.00
3  205,197,952,755.00
4  207,322,431,859.00


CSV file saved: /content/drive/MyDrive/Final project/ETH.csv
Dataframe for sheet 'tips expl':
                                       KEY TAKEAWAYS
0  Treasury Inflation-Protected Securities (TIPS)...
1  The principal value of TIPS rises as inflation...
2  The principal amount is protected since invest...
3  What Are Treasury Inflation-Protected Securiti...
4  Treasury Inflation-Protected Securities (TIPS)...


CSV file saved: /content/drive/MyDrive/Final project/tips expl.csv
List of dataframe names:
['df_oil', 'df_gold', 'df_usd-eur', "df_TIPS'", 'df_BTC', 'df_BNB', 'df_LTC', 'df_XMR', 'df_ETH', 'df_tips_expl']

In [8]:
dataframe_names

['df_oil',
 'df_gold',
 'df_usd-eur',
 "df_TIPS'",
 'df_BTC',
 'df_BNB',
 'df_LTC',
 'df_XMR',
 'df_ETH',
 'df_tips_expl']

In [9]:
#creating columns name
df.columns = df.iloc[0]
df = df.iloc[1:]

In [10]:
df_oil.shape

(679, 6)

In [11]:
df_oil.tail()

                      date monday tuesday wednesday thursday friday
674  2023 May-15 to May-19  75.46   75.15     76.98    75.75  75.42
675  2023 May-22 to May-26  75.77   76.66     77.99    75.66  76.33
676  2023 May-29 to Jun- 2          73.38     71.98    74.18     76
677  2023 Jun- 5 to Jun- 9  76.61   76.22     76.85    75.88  74.74
678  2023 Jun-12 to Jun-16   71.8

In [12]:
display((df_oil.dtypes, '='*40))

(date         object
 monday       object
 tuesday      object
 wednesday    object
 thursday     object
 friday       object
 dtype: object,
 '========================================')

In [13]:
df_oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 679 entries, 0 to 678
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       679 non-null    object
 1   monday     679 non-null    object
 2   tuesday    679 non-null    object
 3   wednesday  679 non-null    object
 4   thursday   679 non-null    object
 5   friday     679 non-null    object
dtypes: object(6)
memory usage: 32.0+ KB